# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conoid < Formula
  desc "A simple HTTP server that can be used to serve static files. It also provides TCP tunnelling through https://localtunnel.me to bypass a firewall or NAT, enabling local development servers to be exposed to the internet."
  homepage ""
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.2/conoid_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "936382d805598fd2f78dcfabc927a4c5c7d21e53549eb21a055bd47b1d5f7ae3"

      def install
        bin.install "conoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.2/conoid_0.0.2_Darwin_arm64.tar.gz"
      sha256 "5d04039027950cae68d7a9cec4810838f4e1be8e9b3e26ca35ca40539066ef9d"

      def install
        bin.install "conoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.2/conoid_0.0.2_Linux_x86_64.tar.gz"
      sha256 "83c85369e4309375b23a5757a139a8ad56a544ac69640f7093ef934b8e349a44"

      def install
        bin.install "conoid"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.2/conoid_0.0.2_Linux_arm64.tar.gz"
      sha256 "34723af4c328ea65f16d2688bbb2b1ec1a02925d086d9b70708170c1fec54ca6"

      def install
        bin.install "conoid"
      end
    end
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{opt_bin}/conoid</string>
      <string>watch</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
  </dict>
</plist>

  EOS
  end
end
