# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conoid < Formula
  desc "A simple HTTP server that can be used to serve static files. It also provides TCP tunnelling through https://localtunnel.me to bypass a firewall or NAT, enabling local development servers to be exposed to the internet."
  homepage ""
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "2e3f6dc00e8d34b82c7a166b8279950f74b1b2e3bfc7f690252c2146ab5f557f"

      def install
        bin.install "conoid"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Darwin_arm64.tar.gz"
      sha256 "802e1d13e965ace130fc1d2e604ff60903163026cd8b2d2938d55ec3f73d4e53"

      def install
        bin.install "conoid"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Linux_arm64.tar.gz"
      sha256 "0889d1fa4f1b52fd11bab3a3e49c507b599b41eb045292416eb3067fd027c75e"

      def install
        bin.install "conoid"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/deestarks/conoid/releases/download/v0.0.1/conoid_0.0.1_Linux_x86_64.tar.gz"
      sha256 "7dd3a4d812c85bd4ad82393e0c22b880d2f386d5791ef8fb0ba5b218ed6cb86c"

      def install
        bin.install "conoid"
      end
    end
  end

  plist_options :startup => false

  def plist; <<~EOS
    <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>#{plist_name}</string>
    <key>ProgramArguments</key>
    <array>
      <string>#{opt_bin}/conoid</string>
      <string>watch</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
  </dict>
</plist>

  EOS
  end
end
